### PR TITLE
Fixes go-openapi#41: Marshal DateTime as DateTime BSON primitive with…

### LINKED ISSUE #41: strfmt. DataTime and GetBson
Hellom i found a strange behavior when persisting the data into mongodb.
The model have a field like that one :
CreatedAt strfmt.DateTime `json:"created_at"`
the model is persised into mongodb using a github.com/globalsign/mgo
Created record inside mongo looks like 
"createdat" : { "data" : "2018-12-04T11:21:10.320Z" }
Excpected record is 
"createdat" : ISODate("2018-12-04T11:21:10.320Z") 

Basically it stores  datatime as bson map instand of ISODate

From what i can see that is because of GetBson function 
https://github.com/go-openapi/strfmt/blob/e471370ae57ac74eaf0afe816a66e4ddd7f1b027/time.go#L177

Can you give me a direction what am I doing wrong ?

### PR DESCRIPTION
**Pull request by PFacheris**
… updated mongoDB driver

Fixes #41

### CODE REVIEW

File: time.go [hunk 1]
```diff
@@ -63,7 +65,7 @@ const (
 
 var (
 	dateTimeFormats = []string{RFC3339Micro, RFC3339Millis, time.RFC3339, time.RFC3339Nano, ISO8601LocalTime}
-	rxDateTime      = regexp.MustCompile(DateTimePattern)
+	rxDateTime	  = regexp.MustCompile(DateTimePattern)
```
Comment (golangcibot) [inline time.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
	rxDateTime      = regexp.MustCompile(DateTimePattern)
```

File: time.go [hunk 2]
```diff
@@ -165,26 +167,46 @@ func (t *DateTime) UnmarshalJSON(data []byte) error {
...
+}
 
-	return errors.New("couldn't unmarshal bson bytes value as Date")
+// UnmarshalBSONValue is an interface implemented by types that can unmarshal a
+// BSON value representation of themselves. The BSON bytes and type can be
+// assumed to be valid. UnmarshalBSONValue must copy the BSON value bytes if it
+// wishes to retain the data after returning.
+func (t *DateTime) UnmarshalBSONValue(tpe bsontype.Type, data []byte) error {
+	i64 := int64(binary.LittleEndian.Uint64(data))
+	// TODO: Use bsonprim.DateTime.Time() method
```
Comment (golangcibot) [inline time.go]: time.go:207: Line contains TODO/BUG/FIXME: "TODO: Use bsonprim.DateTime.Time() metho..." (from `godox`)

File: time.go [hunk 3]
```diff
@@ -165,26 +167,46 @@ func (t *DateTime) UnmarshalJSON(data []byte) error {
...
 }
 
+// UnmarshalBSON reads the DateTime from a BSON document
 func (t *DateTime) UnmarshalBSON(data []byte) error {
-	var m bson.M
-	if err := bson.Unmarshal(data, &m); err != nil {
+	var obj struct {
+		Data DateTime
+	}
+	if err := bson.Unmarshal(data, &obj); err != nil {
```
Comment (golangcibot) [inline time.go]: if statements should only be cuddled with assignments (from `wsl`)

File: time.go [hunk 4]
```diff
@@ -165,26 +167,46 @@ func (t *DateTime) UnmarshalJSON(data []byte) error {
...
 		return err
 	}
+	*t = obj.Data
```
Comment (golangcibot) [inline time.go]: assignments should only be cuddled with other assignments (from `wsl`)

File: time.go [hunk 5]
```diff
@@ -165,26 +167,46 @@ func (t *DateTime) UnmarshalJSON(data []byte) error {
...
+	return nil
```
Comment (golangcibot) [inline time.go]: return statements should not be cuddled if block has more than two lines (from `wsl`)

File: time.go [hunk 6]
```diff
@@ -165,26 +167,46 @@ func (t *DateTime) UnmarshalJSON(data []byte) error {
...
+// BSON document if the error is nil.
+// Marshals a DateTime as a bsontype.DateTime, an int64 representing
+// milliseconds since epoch.
+func (t DateTime) MarshalBSONValue() (bsontype.Type, []byte, error) {
+	// UnixNano cannot be used, the result of calling UnixNano on the zero
+	// Time is undefined.
+	i64 := time.Time(t).Unix() * 1000
+	buf := make([]byte, 8)
+	binary.LittleEndian.PutUint64(buf, uint64(i64))
+	return bsontype.DateTime, buf, nil
```
Comment (golangcibot) [inline time.go]: return statements should not be cuddled if block has more than two lines (from `wsl`)

File: time.go [hunk 7]
```diff
@@ -165,26 +167,46 @@ func (t *DateTime) UnmarshalJSON(data []byte) error {
...
-	return errors.New("couldn't unmarshal bson bytes value as Date")
+// UnmarshalBSONValue is an interface implemented by types that can unmarshal a
+// BSON value representation of themselves. The BSON bytes and type can be
+// assumed to be valid. UnmarshalBSONValue must copy the BSON value bytes if it
+// wishes to retain the data after returning.
+func (t *DateTime) UnmarshalBSONValue(tpe bsontype.Type, data []byte) error {
+	i64 := int64(binary.LittleEndian.Uint64(data))
+	// TODO: Use bsonprim.DateTime.Time() method
+	*t = DateTime(time.Unix(i64/1000, i64%1000*1000000))
+	return nil
```
Comment (golangcibot) [inline time.go]: return statements should not be cuddled if block has more than two lines (from `wsl`)

File: time.go (hunk 2 above)
Comment (fredbi) [reply time.go]: You can keep your code and. Disabled the most pedantic new godox linter from golangci.yaml

Comment (fredbi) [reply time.go]: Never mind: I'll do the linting parameter chore.
